sudo: false
language: python
python:
  - "3.5"
env:
  - TOX_ENV=py26-dj14
  - TOX_ENV=py26-dj15
  - TOX_ENV=py26-dj16
  - TOX_ENV=py27-dj14
  - TOX_ENV=py27-dj15
  - TOX_ENV=py27-dj16
  - TOX_ENV=py27-dj17
  - TOX_ENV=py27-dj18
  - TOX_ENV=py27-dj19
  - TOX_ENV=py32-dj15
  - TOX_ENV=py32-dj16
  - TOX_ENV=py32-dj17
  - TOX_ENV=py32-dj18
  - TOX_ENV=py33-dj15
  - TOX_ENV=py33-dj16
  - TOX_ENV=py33-dj17
  - TOX_ENV=py33-dj18
  - TOX_ENV=py34-dj15
  - TOX_ENV=py34-dj16
  - TOX_ENV=py34-dj17
  - TOX_ENV=py34-dj18
  - TOX_ENV=py34-dj19
  - TOX_ENV=py35-dj19

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

after_success:
  - pip install coveralls==0.5
  - coveralls
