language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - DJANGO_VERSION=1.4.15
  - DJANGO_VERSION=1.5.10
  - DJANGO_VERSION=1.6.7
  - DJANGO_VERSION=1.7

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q Pillow
  - pip install -q djangorestframework
  - pip install coveralls
  - python setup.py -q develop

script: coverage run --source=djet testproject/manage.py test tests
after_success:
  coveralls

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION=1.7
    - python: "3.2"
      env: DJANGO_VERSION=1.4.15
    - python: "3.3"
      env: DJANGO_VERSION=1.4.15
    - python: "3.4"
      env: DJANGO_VERSION=1.4.15
