language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.10
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q Pillow
  - python setup.py -q install
script: testproject/manage.py test